import os
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch

os.makedirs('test_docs/authentic', exist_ok=True)
os.makedirs('test_docs/forged', exist_ok=True)

def create_pdf(path, title, content_lines, is_forged=False):
    c = canvas.Canvas(path, pagesize=letter)
    
    # Metadata forgery
    if is_forged:
        c.setCreator("Adobe Acrobat Pro 2021") # Signal of potential tampering in some contexts
        c.setAuthor("Unknown User")
    else:
        c.setCreator("Official Document Generator v1.0")
        c.setAuthor("Government Authority")
        
    c.setFont("Helvetica-Bold", 16)
    c.drawString(1 * inch, 10 * inch, title)
    
    c.setFont("Helvetica", 12)
    y = 9.5 * inch
    for line in content_lines:
        c.drawString(1 * inch, y, line)
        y -= 0.3 * inch
        
    if is_forged:
        c.setFont("Helvetica-Oblique", 10)
        c.setFillColorRGB(0.8, 0.8, 0.8)
        c.drawString(1 * inch, 1 * inch, "Generated by Trial Version - Do Not Use")
        
    c.save()

# --- Authentic Documents ---

# Financial
create_pdf(
    'test_docs/authentic/Bank_Statement_Rajesh.pdf',
    'Bank Statement - State Bank of India',
    [
        'Account Holder: Rajesh Kumar M.',
        'Account Number: 3192XXXXX841',
        'Period: 01-Jan-2025 to 31-Mar-2025',
        'Opening Balance: ₹ 1,50,000',
        'Total Credits: ₹ 5,00,000',
        'Total Debits: ₹ 4,00,000',
        'Closing Balance: ₹ 2,50,000', # Math is correct
        'End of Statement'
    ]
)

create_pdf(
    'test_docs/authentic/ITR_Rajesh_FY24.pdf',
    'Income Tax Return (ITR-V)',
    [
        'Name: Rajesh Kumar M.',
        'PAN: ABCDE1234F',
        'Assessment Year: 2024-25',
        'Gross Total Income: ₹ 12,00,000',
        'Total Deductions: ₹ 1,50,000',
        'Total Income: ₹ 10,50,000',
        'Tax Paid: ₹ 1,20,000',
        'Verification Status: E-Verified'
    ]
)

create_pdf(
    'test_docs/authentic/PnL_Rajesh_Business.pdf',
    'Profit & Loss Statement',
    [
        'Business: Rajesh Enterprises',
        'Financial Year: 2024-25',
        'Revenue from Operations: ₹ 50,00,000',
        'Cost of Goods Sold: ₹ 30,00,000',
        'Gross Profit: ₹ 20,00,000',
        'Operating Expenses: ₹ 8,00,000',
        'Net Profit: ₹ 12,00,000' # Math is correct
    ]
)

# Legal
create_pdf(
    'test_docs/authentic/Sale_Deed_Property_42.pdf',
    'Sale Deed',
    [
        'This Sale Deed is made on 15-Jun-2023',
        'Vendor: Suresh Patel',
        'Purchaser: Rajesh Kumar M.',
        'Property: Plot 42, Green Valley, Pune',
        'Consideration Amount: ₹ 75,00,000',
        'Stamp Duty Paid: ₹ 4,50,000',
        'Registered at Sub-Registrar Office, Haveli-1'
    ]
)

create_pdf(
    'test_docs/authentic/Power_Of_Attorney.pdf',
    'General Power of Attorney',
    [
        'Principal: Ramesh Kumar M.',
        'Attorney: Rajesh Kumar M.',
        'Date of Execution: 10-Jan-2024',
        'Powers Granted: Property management, banking operations',
        'Valid until: Revoked',
        'Signed and Notarized'
    ]
)

create_pdf(
    'test_docs/authentic/CoI_Rajesh_Enterprises.pdf',
    'Certificate of Incorporation',
    [
        'Company Name: Rajesh Enterprises Pvt Ltd',
        'CIN: U12345MH2020PTC987654',
        'Date of Incorporation: 05-May-2020',
        'Registrar of Companies: Mumbai',
        'Authorized Capital: ₹ 10,00,000'
    ]
)

# Identity
create_pdf(
    'test_docs/authentic/Aadhaar_Rajesh.pdf',
    'Aadhaar Card',
    [
        'Name: Rajesh Kumar M.',
        'DOB: 12-Aug-1985',
        'Gender: Male',
        'Aadhaar Number: 1234 5678 9012',
        'Address: 402, Sai Kripa Apts, Pune, 411001',
        'UIDAI Authentic Document'
    ]
)

create_pdf(
    'test_docs/authentic/PAN_Rajesh.pdf',
    'Permanent Account Number (PAN) Card',
    [
        'Income Tax Department, Govt. of India',
        'Name: Rajesh Kumar M.',
        'Father Name: Mahesh Kumar',
        'DOB: 12-Aug-1985',
        'PAN: ABCDE1234F'
    ]
)

create_pdf(
    'test_docs/authentic/Passport_Rajesh.pdf',
    'Republic of India - Passport',
    [
        'Type: P',
        'Country Code: IND',
        'Passport No: Z9876543',
        'Surname: M.',
        'Given Name: Rajesh Kumar',
        'Nationality: Indian',
        'DOB: 12-Aug-1985',
        'Place of Birth: Mumbai',
        'Date of Issue: 01-Jan-2020',
        'Date of Expiry: 31-Dec-2029'
    ]
)


# --- Forged Documents ---

# 1. Financial Forgery (Math Inconsistency)
create_pdf(
    'test_docs/forged/Bank_Statement_Rajesh_FORGED.pdf',
    'Bank Statement - State Bank of India',
    [
        'Account Holder: Rajesh Kumar M.',
        'Account Number: 3192XXXXX841',
        'Period: 01-Jan-2025 to 31-Mar-2025',
        'Opening Balance: ₹ 1,50,000',
        'Total Credits: ₹ 5,00,000',
        'Total Debits: ₹ 4,00,000',
        'Closing Balance: ₹ 8,50,000', # FORGED: Math is wrong (1.5 + 5 - 4 != 8.5)
        'End of Statement'
    ],
    is_forged=True
)

create_pdf(
    'test_docs/forged/PnL_Rajesh_Business_FORGED.pdf',
    'Profit & Loss Statement',
    [
        'Business: Rajesh Enterprises',
        'Financial Year: 2024-25',
        'Revenue from Operations: ₹ 50,00,000',
        'Cost of Goods Sold: ₹ 30,00,000',
        'Gross Profit: ₹ 35,00,000', # FORGED: Math is wrong (50 - 30 != 35)
        'Operating Expenses: ₹ 8,00,000',
        'Net Profit: ₹ 27,00,000' # Continuing the math error
    ],
    is_forged=True
)


# 2. Legal Forgery (Metadata & Date inconsistencies)
create_pdf(
    'test_docs/forged/Sale_Deed_Property_42_FORGED.pdf',
    'Sale Deed',
    [
        'This Sale Deed is made on 15-Jun-2023',
        'Vendor: Suresh Patel',
        'Purchaser: Rajesh Kumar M.',
        'Property: Plot 42, Green Valley, Pune',
        'Consideration Amount: ₹ 75,00,000',
        'Stamp Duty Paid: ₹ 4,50,000',
        'Registered at Sub-Registrar Office, Haveli-1',
        'Date of Registration: 10-Jun-2023' # FORGED: Registration before deed making
    ],
    is_forged=True
)

# 3. Identity Forgery (Mismatching details across docs)
create_pdf(
    'test_docs/forged/PAN_Rajesh_FORGED.pdf',
    'Permanent Account Number (PAN) Card',
    [
        'Income Tax Department, Govt. of India',
        'Name: Rajesh Kumar M.',
        'Father Name: Mahesh Kumar',
        'DOB: 12-Aug-1988', # FORGED: DOB altered to make him younger
        'PAN: ABCDE1234F'
    ],
    is_forged=True
)

print("Generated test documents successfully in test_docs/authentic and test_docs/forged")
